spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/posts_json_exercises
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true

  graphql:
    graphiql:
      enabled: true

  data:
    jpa:
      repositories:
        enabled: true
